on:
  issue_comment:
    types: [created, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job01:
    if: "contains(github.event.comment.html_url, '/pull/') && (contains(github.event.comment.body, 'commenttest') || contains(github.event.comment.body, 'netlify'))"
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: "${{ toJson(github) }}"
        name: "Dump GitHub context"
        run: 'echo "$GITHUB_CONTEXT"'
      - name: "get pullrequest url"
        run: echo "${{ github.event.issue.pull_request.url }}"
      - name: "echo upstream branch"
        run: "echo ${{ steps.upstreambranch.outputs.branchname }}\n"
      - name: Checkout Pull Request
        env:
          PR_NUM: ""
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "${{PR_NUM}}"
      - name: "echo Comment"
        run: echo "${{ github.event.comment.body }}\n"
      - name: PR Comment
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          issue-number: ${{ toJson(github.event.pull_request.number) }}
          script: |
            github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Hello World'
            })
